// <auto-generated />
using System;
using EComercial.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EComercial.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20191204164155_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("EComercial.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiredDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("product_description")
                        .HasColumnType("TEXT");

                    b.Property<string>("product_image")
                        .HasColumnType("TEXT");

                    b.Property<string>("product_name")
                        .HasColumnType("TEXT");

                    b.Property<int>("product_price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
